services:
  app:
    environment:
      MANAGEMENT_OTLP_METRICS_EXPORT_ENABLED: "true"
      MANAGEMENT_OTLP_METRICS_EXPORT_URL: http://otel-collector:4318/v1/metrics
      MANAGEMENT_OTLP_METRICS_EXPORT_STEP: 5s
      MANAGEMENT_OTLP_TRACING_ENDPOINT: http://otel-collector:4318/v1/traces
      MANAGEMENT_TRACING_ENABLED: "true"
      MANAGEMENT_TRACING_SAMPLING_PROBABILITY: "1.0"
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4318
      OTEL_SERVICE_NAME: itau-balance-api
    depends_on:
      otel-collector:
        condition: service_started
