services:
  app:
    environment:
      MANAGEMENT_OTLP_METRICS_EXPORT_ENABLED: "true"
      MANAGEMENT_OTLP_METRICS_EXPORT_STEP: 5s
      MANAGEMENT_TRACING_ENABLED: "true"
      MANAGEMENT_TRACING_SAMPLING_PROBABILITY: "1.0"
      MANAGEMENT_OPENTELEMETRY_TRACING_EXPORT_OTLP_ENDPOINT: http://otel-collector:4317
      MANAGEMENT_OPENTELEMETRY_TRACING_EXPORT_OTLP_TRANSPORT: grpc
      MANAGEMENT_OPENTELEMETRY_METRICS_EXPORT_OTLP_ENDPOINT: http://otel-collector:4317
      OTEL_SERVICE_NAME: itau-balance-api
    depends_on:
      otel-collector:
        condition: service_started
